apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-github-8m6z30rhb7tmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-github-8m6z30rhb7tmn
    app.kubernetes.io/part-of: application-github-vrxevvmjp1po3
  name: component-github-8m6z30rhb7tmn
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-github-8m6z30rhb7tmn
status:
  loadBalancer: {}
